# $Id: //WIFI_SOC/release/SDK_4_1_0_0/source/linux-2.6.36.x/arch/cris/arch-v32/mach-fs/Makefile#1 $
#
# Makefile for the linux kernel.
#

obj-y   := dma.o pinmux.o io.o arbiter.o
bj-$(CONFIG_ETRAX_VCS_SIM) += vcs_hook.o
obj-$(CONFIG_CPU_FREQ)   += cpufreq.o

clean:

